-- Intentionally empty. Data is loaded by the ETL pipeline (etl/run_etl.py) or, for a
-- self-contained local run, by scripts/seed_demo.py, not from a seed file. This file
-- exists so docker compose init succeeds.
